services:
  - type: web
    name: FEKDI-BI
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn test:app
    envVars:
      - key: PIP_NO_CACHE_DIR
        value: true
    apt:
      packages:
        - graphviz
