services:
  - type: web
    name: FEKDI-BI
    env: python
    buildCommand: |
      apt-get update && apt-get install -y graphviz
      pip install -r requirements.txt
    startCommand: |
      export PATH=$PATH:/usr/bin
      gunicorn test:app
